### ISSUE TITLE
是否需要在node-site-config.json中的httpsAgent填写具体内容？

### ISSUE THREAD

**Issue by ZhaoKuanhong** [22earth/rss2pan#1]
我直接使用实例中的`"httpsAgent": "httpsAgent"`, 运行后无任何提示，抓包仅抓到访问` proapi.115.com` ，未发现有访问rss的连接。
是否是要修改此处内容？谢谢！
![image](https://user-images.githubusercontent.com/23447931/199153339-fa3601b4-3a0a-4421-b482-47d62e3c597e.png)
![image](https://user-images.githubusercontent.com/23447931/199153381-33cf1f69-dffc-45fe-a497-97009a2f1a60.png)

**Comment by 22earth** [comment]
设置【httsAgent】会使用代理。默认使用的地址 http://127.0.0.1:10809。 要确保你的电脑的梯子是这个配置。
具体查看： https://github.com/22earth/rss2pan#proxy-%E9%85%8D%E7%BD%AE

如果你的电脑或者服务器能够直连  share.dmhy.org 。可以删掉第二张截图里面的配置。

**Comment by 22earth** [comment]
才注意到。你第一项配置错了。  你设置的是 mikanni.me 的 rss 源。所以应该是
```json
{
  "mikanani.me": [
    {
      "name": "test",
      "filter": "/简体|1080p/",
      "url": "https://mikanani.me/RSS/Bangumi?bangumiId=2739&subgroupid=12"
    }
  ]
}
```

**Comment by ZhaoKuanhong** [comment]
> 才注意到。你第一项配置错了。 你设置的是 mikanni.me 的 rss 源。所以应该是
> 
> ```json
> {
>   "mikanani.me": [
>     {
>       "name": "test",
>       "filter": "/简体|1080p/",
>       "url": "https://mikanani.me/RSS/Bangumi?bangumiId=2739&subgroupid=12"
>     }
>   ]
> }
> ```

哦哦 我一开始是用的dmhy，直接改过来的，没注意，谢谢

**Comment by ZhaoKuanhong** [comment]
还有`readme`里
![image](https://user-images.githubusercontent.com/23447931/199166247-cb094730-993a-4c1c-8b04-cbe205293a6a.png)
cid处是不是少了一个引号

**Comment by 22earth** [comment]
> 

对。是我写错了。我还一直奇怪，颜色不对劲。
